In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv('nba.csv')
df.head()

Patient_ID  Age  Gender Chest_Pain  Cough_Severity  Breathlessness  Fatigue  \
0  PID000001   69    Male        Yes               1               2        3   
1  PID000002   32  Female        Yes               3               0        9   
2  PID000003   89    Male         No               7               0        3   
3  PID000004   78  Female        Yes               2               0        6   
4  PID000005   38    Male         No               7               2        5   

   Weight_Loss     Fever Night_Sweats Sputum_Production Blood_in_Sputum  \
0         2.37  Moderate          Yes            Medium             Yes   
1         6.09  Moderate           No            Medium              No   
2         2.86      Mild          Yes            Medium              No   
3         4.57  Moderate           No              High             Yes   
4        13.86      High          Yes               Low              No   

  Smoking_History Previous_TB_History         Class  
0          Former                 Yes        Normal  
1         Current                 Yes        Normal  
2         Current                  No  Tuberculosis  
3           Never                 Yes  Tuberculosis  
4           Never                 Yes  Tuberculosis

In [4]:
df.isnull().sum()

Patient_ID             0
Age                    0
Gender                 0
Chest_Pain             0
Cough_Severity         0
Breathlessness         0
Fatigue                0
Weight_Loss            0
Fever                  0
Night_Sweats           0
Sputum_Production      0
Blood_in_Sputum        0
Smoking_History        0
Previous_TB_History    0
Class                  0
dtype: int64

In [5]:
df.describe()

Age  Cough_Severity  Breathlessness       Fatigue  \
count  20000.000000    20000.000000    20000.000000  20000.000000   
mean      53.467450        4.491350        2.003450      4.508450   
std       20.773984        2.864723        1.417123      2.881552   
min       18.000000        0.000000        0.000000      0.000000   
25%       35.000000        2.000000        1.000000      2.000000   
50%       53.000000        4.000000        2.000000      5.000000   
75%       71.000000        7.000000        3.000000      7.000000   
max       89.000000        9.000000        4.000000      9.000000   

        Weight_Loss  
count  20000.000000  
mean       7.455281  
std        4.339864  
min        0.000000  
25%        3.640000  
50%        7.490000  
75%       11.200000  
max       15.000000

In [6]:
df.shape

(20000, 15)

In [7]:
df_encoded = df.copy()
for col in df_encoded.select_dtypes(include='object').columns:
    df_encoded[col] = LabelEncoder().fit_transform(df_encoded[col])

In [8]:
X = df_encoded.drop(['Class'], axis=1)
y = df_encoded['Class']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [11]:
y_pred = model.predict(X_test)

In [12]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy : 0.6965

Confusion Matrix:
 [[2786    0]
 [1214    0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.70      1.00      0.82      2786
           1       0.00      0.00      0.00      1214

    accuracy                           0.70      4000
   macro avg       0.35      0.50      0.41      4000
weighted avg       0.49      0.70      0.57      4000



C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificatio

In [13]:
model.predict([[1,19,1,0,2,4,1,0,2,1,3,0,7,1]])

C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [14]:
import joblib 
joblib.dump(model,'TB_model.pkl')

['TB_model.pkl']

In [15]:
model=joblib.load('TB_model.pkl')
model.predict([[1,19,1,0,2,4,1,0,2,1,3,0,7,1]])

C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [16]:
df

Patient_ID  Age  Gender Chest_Pain  Cough_Severity  Breathlessness  \
0      PID000001   69    Male        Yes               1               2   
1      PID000002   32  Female        Yes               3               0   
2      PID000003   89    Male         No               7               0   
3      PID000004   78  Female        Yes               2               0   
4      PID000005   38    Male         No               7               2   
...          ...  ...     ...        ...             ...             ...   
19995  PID019996   53    Male         No               0               4   
19996  PID019997   27  Female         No               3               1   
19997  PID019998   23    Male         No               1               2   
19998  PID019999   24  Female         No               8               4   
19999  PID020000   48    Male         No               9               4   

       Fatigue  Weight_Loss     Fever Night_Sweats Sputum_Production  \
0            3         2.37  Moderate          Yes            Medium   
1            9         6.09  Moderate           No            Medium   
2            3         2.86      Mild          Yes            Medium   
3            6         4.57  Moderate           No              High   
4            5        13.86      High          Yes               Low   
...        ...          ...       ...          ...               ...   
19995        6        11.72  Moderate          Yes            Medium   
19996        1         5.67  Moderate          Yes               Low   
19997        8         3.91      High          Yes               Low   
19998        6         8.77  Moderate          Yes            Medium   
19999        4         4.84      High           No              High   

      Blood_in_Sputum Smoking_History Previous_TB_History         Class  
0                 Yes          Former                 Yes        Normal  
1                  No         Current                 Yes        Normal  
2                  No         Current                  No  Tuberculosis  
3                 Yes           Never                 Yes  Tuberculosis  
4                  No           Never                 Yes  Tuberculosis  
...               ...             ...                 ...           ...  
19995              No           Never                 Yes        Normal  
19996             Yes         Current                 Yes  Tuberculosis  
19997             Yes           Never                  No        Normal  
19998             Yes           Never                 Yes        Normal  
19999              No           Never                 Yes        Normal  

[20000 rows x 15 columns]